version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: 'Disabled'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
        BUNDLE_FORCE_RUBY_PLATFORM: '1'
    image: chatwoot:production
    restart: always
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
    env_file: .env
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - postgres
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: 'Disabled'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
        BUNDLE_FORCE_RUBY_PLATFORM: '1'
    image: chatwoot:production
    restart: always
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
    env_file: .env
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    depends_on:
      - postgres
      - redis
      - rails

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-chatwoot_production}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"${REDIS_PASSWORD}\""]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

